%% Affective Ratings: Correlations and Plots by Gender
 
% Setup and create folders
resultsFolder = 'results/a02_sam_analysis';
figuresFolder = fullfile(resultsFolder, 'figures_sam_correlations');
if ~exist(resultsFolder, 'dir')
    mkdir(resultsFolder);
end
if ~exist(figuresFolder, 'dir')
    mkdir(figuresFolder);
end

% File path for the text file and open file for writing
txtFile = fullfile(resultsFolder, 'sam_correlations.txt');
fileID = fopen(txtFile, 'w');


%% Data preparation

% Group images by valence
positive = (img.Valence == 'positive');
negative = (img.Valence == 'negative');

% Identify images that showed significant gender effects in the U-Tests
% (pFDR <= 0.05 for pleasure and/or arousal and/or dominance)
sigIdx_pos = (img.pFDR_pleasure_pos <= 0.05) | (img.pFDR_arousal_pos <= 0.05) | (img.pFDR_dominance_pos <= 0.05);
sigIdx_neg = (img.pFDR_pleasure_neg <= 0.05) | (img.pFDR_arousal_neg <= 0.05) | (img.pFDR_dominance_neg <= 0.05);

%% Plot Pleasure against Arousal Mean Ratings for Pictures by Gender (and Valence)

% Plot
f = figure;
hold on;

% Plot female pleasant data points
scatter(img.arousal_mean_female(positive), img.pleasure_mean_female(positive), ...
        60, 'o', ...
        'MarkerFaceColor', femaleColor, ...
        'MarkerFaceAlpha', 0.7, ...
        'MarkerEdgeColor', 'none', ...
        'DisplayName', 'Female');

% Plot male pleasant data points
scatter(img.arousal_mean_male(positive), img.pleasure_mean_male(positive), ...
        60, 'o', ...
        'MarkerFaceColor', maleColor, ...
        'MarkerFaceAlpha', 0.7, ...
        'MarkerEdgeColor', 'none', ...
        'DisplayName', 'Male');

% Plot female unpleasant data points
scatter(img.arousal_mean_female(negative), img.pleasure_mean_female(negative), ...
        60, 'o', ...
        'MarkerFaceColor', femaleColor, ...
        'MarkerFaceAlpha', 0.7, ...
        'MarkerEdgeColor', 'none', ...
        'HandleVisibility', 'off');

% Plot male unpleasant data points
scatter(img.arousal_mean_male(negative), img.pleasure_mean_male(negative), ...
        60, 'o', ...
        'MarkerFaceColor', maleColor, ...
        'MarkerFaceAlpha', 0.7, ...
        'MarkerEdgeColor', 'none', ...
        'HandleVisibility', 'off');


% Highlight images with significant gender effects in U-Tests (after FDR correction)

scatter(img.arousal_mean_female(sigIdx_pos), ...
        img.pleasure_mean_female(sigIdx_pos), ...
        60, 'o', ...
        'MarkerEdgeColor', 'k', ...
        'MarkerFaceColor', femaleColor, ...
        'MarkerEdgeAlpha', 0.7, ...
        'MarkerFaceAlpha', 0.7, ...
        'LineWidth', 0.7, ...
        'HandleVisibility', 'off');

scatter(img.arousal_mean_male(sigIdx_pos), ...
        img.pleasure_mean_male(sigIdx_pos), ...
        60, 'o', ...
        'MarkerEdgeColor', 'k', ...
        'MarkerFaceColor', maleColor, ...
        'MarkerEdgeAlpha', 0.7, ...
        'MarkerFaceAlpha', 0.7, ...
        'LineWidth', 0.7, ...
        'HandleVisibility', 'off');

scatter(img.arousal_mean_female(sigIdx_neg), ...
        img.pleasure_mean_female(sigIdx_neg), ...
        60, 'o', ...
        'MarkerEdgeColor', 'k', ...
        'MarkerFaceColor', femaleColor, ...
        'MarkerEdgeAlpha', 0.7, ...
        'MarkerFaceAlpha', 0.7, ...
        'LineWidth', 0.7, ...
        'HandleVisibility', 'off');

scatter(img.arousal_mean_male(sigIdx_neg), ...
        img.pleasure_mean_male(sigIdx_neg), ...
        60, 'o', ...
        'MarkerEdgeColor', 'k', ...
        'MarkerFaceColor', maleColor, ...
        'MarkerEdgeAlpha', 0.7, ...
        'MarkerFaceAlpha', 0.7, ...
        'LineWidth', 0.7, ...
        'HandleVisibility', 'off');

% Title, labels, legend
xlabel('Arousal');
ylabel('Pleasure');
title('Pleasure vs. Arousal by Gender');
legend('Location', 'best');
grid on;
axis square;

% save figure
exportgraphics(f, fullfile(figuresFolder, 'Arousal_Pleasure_plot.png'), 'Resolution', 300);

%% Plot Pleasure against Dominance Mean Ratings for Pictures by Gender (and Valence)

% Plot
f = figure;
hold on;


% Plot data points

scatter(img.dominance_mean_female(positive), img.pleasure_mean_female(positive), ...
        60, 'o', ...
        'MarkerFaceColor', femaleColor, ...
        'MarkerFaceAlpha', 0.7, ...
        'MarkerEdgeColor', 'none', ...
        'DisplayName', 'Female');

scatter(img.dominance_mean_male(positive), img.pleasure_mean_male(positive), ...
        60, 'o', ...
        'MarkerFaceColor', maleColor, ...
        'MarkerFaceAlpha', 0.7, ...
        'MarkerEdgeColor', 'none', ...
        'DisplayName', 'Male');

scatter(img.dominance_mean_female(negative), img.pleasure_mean_female(negative), ...
        60, 'o', ...
        'MarkerFaceColor', femaleColor, ...
        'MarkerFaceAlpha', 0.7, ...
        'MarkerEdgeColor', 'none', ...
        'HandleVisibility', 'off');

scatter(img.dominance_mean_male(negative), img.pleasure_mean_male(negative), ...
        60, 'o', ...
        'MarkerFaceColor', maleColor, ...
        'MarkerFaceAlpha', 0.7, ...
        'MarkerEdgeColor', 'none', ...
        'HandleVisibility', 'off');


% Highlight images with significant gender effects in U-Tests (after FDR correction)

scatter(img.dominance_mean_female(sigIdx_pos), ...
        img.pleasure_mean_female(sigIdx_pos), ...
        60, 'o', ...
        'MarkerEdgeColor', 'k', ...
        'MarkerFaceColor', femaleColor, ...
        'MarkerEdgeAlpha', 0.7, ...
        'MarkerFaceAlpha', 0.7, ...
        'LineWidth', 0.7, ...
        'HandleVisibility', 'off');  

scatter(img.dominance_mean_male(sigIdx_pos), ...
        img.pleasure_mean_male(sigIdx_pos), ...
        60, 'o', ...
        'MarkerEdgeColor', 'k', ...
        'MarkerFaceColor', maleColor, ...
        'MarkerEdgeAlpha', 0.7, ...
        'MarkerFaceAlpha', 0.7, ...
        'LineWidth', 0.7, ...
        'HandleVisibility', 'off');  

scatter(img.dominance_mean_female(sigIdx_neg), ...
        img.pleasure_mean_female(sigIdx_neg), ...
        60, 'o', ...
        'MarkerEdgeColor', 'k', ...
        'MarkerFaceColor', femaleColor, ...
        'MarkerEdgeAlpha', 0.7, ...
        'MarkerFaceAlpha', 0.7, ...
        'LineWidth', 0.7, ...
        'HandleVisibility', 'off');

scatter(img.dominance_mean_male(sigIdx_neg), ...
        img.pleasure_mean_male(sigIdx_neg), ...
        60, 'o', ...
        'MarkerEdgeColor', 'k', ...
        'MarkerFaceColor', maleColor, ...
        'MarkerEdgeAlpha', 0.7, ...
        'MarkerFaceAlpha', 0.7, ...
        'LineWidth', 0.7, ...
        'HandleVisibility', 'off');  

% Title, labels, legend
xlabel('Dominance');
ylabel('Pleasure');
title('Pleasure vs. Dominance by Gender');
legend('Location', 'best');
grid on;
axis square;

% save figure
exportgraphics(f, fullfile(figuresFolder, 'Dominance_Pleasure_plot.png'), 'Resolution', 300);

%% Plot Arousal against Dominance Mean Ratings for Pictures by Gender (and Valence)

% Plot
f = figure;
hold on;


% Plot data points

scatter(img.dominance_mean_female(positive), img.arousal_mean_female(positive), ...
        60, 'o', ...
        'MarkerFaceColor', femaleColor, ...
        'MarkerFaceAlpha', 0.7, ...
        'MarkerEdgeColor', 'none', ...
        'DisplayName', 'Female');

scatter(img.dominance_mean_male(positive), img.arousal_mean_male(positive), ...
        60, 'o', ...
        'MarkerFaceColor', maleColor, ...
        'MarkerFaceAlpha', 0.7, ...
        'MarkerEdgeColor', 'none', ...
        'DisplayName', 'Male');

scatter(img.dominance_mean_female(negative), img.arousal_mean_female(negative), ...
        60, 'o', ...
        'MarkerFaceColor', femaleColor, ...
        'MarkerFaceAlpha', 0.7, ...
        'MarkerEdgeColor', 'none', ...
        'HandleVisibility', 'off');

scatter(img.dominance_mean_male(negative), img.arousal_mean_male(negative), ...
        60, 'o', ...
        'MarkerFaceColor', maleColor, ...
        'MarkerFaceAlpha', 0.7, ...
        'MarkerEdgeColor', 'none', ...
        'HandleVisibility', 'off');


% Highlight images with significant gender effects in U-Tests (after FDR correction)

scatter(img.dominance_mean_female(sigIdx_pos), ...
        img.arousal_mean_female(sigIdx_pos), ...
        60, 'o', ...
        'MarkerEdgeColor', 'k', ...
        'MarkerFaceColor', femaleColor, ...
        'MarkerEdgeAlpha', 0.7, ...
        'MarkerFaceAlpha', 0.7, ...
        'LineWidth', 0.7, ...
        'HandleVisibility', 'off');  

scatter(img.dominance_mean_male(sigIdx_pos), ...
        img.arousal_mean_male(sigIdx_pos), ...
        60, 'o', ...
        'MarkerEdgeColor', 'k', ...
        'MarkerFaceColor', maleColor, ...
        'MarkerEdgeAlpha', 0.7, ...
        'MarkerFaceAlpha', 0.7, ...
        'LineWidth', 0.7, ...
        'HandleVisibility', 'off');

scatter(img.dominance_mean_female(sigIdx_neg), ...
        img.arousal_mean_female(sigIdx_neg), ...
        60, 'o', ...
        'MarkerEdgeColor', 'k', ...
        'MarkerFaceColor', femaleColor, ...
        'MarkerEdgeAlpha', 0.7, ...
        'MarkerFaceAlpha', 0.7, ...
        'LineWidth', 0.7, ...
        'HandleVisibility', 'off'); 

scatter(img.dominance_mean_male(sigIdx_neg), ...
        img.arousal_mean_male(sigIdx_neg), ...
        60, 'o', ...
        'MarkerEdgeColor', 'k', ...
        'MarkerFaceColor', maleColor, ...
        'MarkerEdgeAlpha', 0.7, ...
        'MarkerFaceAlpha', 0.7, ...
        'LineWidth', 0.7, ...
        'HandleVisibility', 'off');

% Title, labels, legend
xlabel('Dominance');
ylabel('Arousal');
title('Arousal vs. Dominance by Gender');
legend('Location', 'best');
grid on;
axis square;

% save figure
exportgraphics(f, fullfile(figuresFolder, 'Dominance_Arousal_plot.png'), 'Resolution', 300);

%% Calculate correlations between affective dimensions (by gender and valence)

% Print header
fprintf(fileID, '\n--- Affective Experience Dimensions Correlations ---\n\n');

% Compute and write correlations
[r1, p1] = corr(sam.Pleasure, sam.Arousal, 'Type', 'Spearman');
fprintf(fileID, 'Pleasure vs. Arousal:     r = %.2f,   p = %.4f\n', r1, p1);

[r2, p2] = corr(sam.Pleasure, sam.Dominance, 'Type', 'Spearman');
fprintf(fileID, 'Pleasure vs. Dominance:   r = %.2f,   p = %.4f\n', r2, p2);

[r3, p3] = corr(sam.Arousal, sam.Dominance, 'Type', 'Spearman');
fprintf(fileID, 'Arousal vs. Dominance:    r = %.2f,   p = %.4f\n', r3, p3);


% Print header
fprintf(fileID, '\n\n--- Correlations by Valence ---\n\n');

% Compute and write correlations (pleasant stimuli)
[r1, p1] = corr(sam_pos.Pleasure, sam_pos.Arousal, 'Type', 'Spearman');
fprintf(fileID, 'Positive: \nPleasure vs. Arousal:     r = %.2f,   p = %.4f\n', r1, p1);

[r2, p2] = corr(sam_pos.Pleasure, sam_pos.Dominance, 'Type', 'Spearman');
fprintf(fileID, 'Pleasure vs. Dominance:   r = %.2f,   p = %.4f\n', r2, p2);

[r3, p3] = corr(sam_pos.Arousal, sam_pos.Dominance, 'Type', 'Spearman');
fprintf(fileID, 'Arousal vs. Dominance:    r = %.2f,   p = %.4f\n', r3, p3);

% Compute and write correlations (unpleasant stimuli)
[r1, p1] = corr(sam_neg.Pleasure, sam_neg.Arousal, 'Type', 'Spearman');
fprintf(fileID, '\nNegative: \nPleasure vs. Arousal:     r = %.2f,   p = %.4f\n', r1, p1);

[r2, p2] = corr(sam_neg.Pleasure, sam_neg.Dominance, 'Type', 'Spearman');
fprintf(fileID, 'Pleasure vs. Dominance:   r = %.2f,   p = %.4f\n', r2, p2);

[r3, p3] = corr(sam_neg.Arousal, sam_neg.Dominance, 'Type', 'Spearman');
fprintf(fileID, 'Arousal vs. Dominance:    r = %.2f,   p = %.4f\n', r3, p3);


% Group by gender in addition to by valence
fp = (sam_pos.Gender == "female");
mp = (sam_pos.Gender == "male");
fn = (sam_neg.Gender == "female");
mn = (sam_neg.Gender == "male");


% Print header
fprintf(fileID, '\n\n--- Correlations by Gender ---\n');

% Compute and write correlations
[r1, p1] = corr(sam.Pleasure(sam.Gender == 'female'), sam.Arousal(sam.Gender == 'female'), 'Type', 'Spearman');
fprintf(fileID, '\nWomen: \nPleasure vs. Arousal:     r = %.2f,   p = %.4f\n', r1, p1);
rF = r1;

% Compute and write correlations
[r1, p1] = corr(sam.Pleasure(sam.Gender == 'female'), sam.Dominance(sam.Gender == 'female'), 'Type', 'Spearman');
fprintf(fileID, 'Pleasure vs. Dominance:     r = %.2f,   p = %.4f\n', r1, p1);
rF = r1;

% Compute and write correlations
[r1, p1] = corr(sam.Dominance(sam.Gender == 'female'), sam.Arousal(sam.Gender == 'female'), 'Type', 'Spearman');
fprintf(fileID, 'Dominance vs. Arousal:     r = %.2f,   p = %.4f\n', r1, p1);
rF = r1;

% Compute and write correlations
[r1, p1] = corr(sam.Pleasure(sam.Gender == 'male'), sam.Arousal(sam.Gender == 'male'), 'Type', 'Spearman');
fprintf(fileID, '\nMen: \nPleasure vs. Arousal:     r = %.2f,   p = %.4f\n', r1, p1);
rM = r1;

% Compute and write correlations
[r1, p1] = corr(sam.Pleasure(sam.Gender == 'male'), sam.Dominance(sam.Gender == 'male'), 'Type', 'Spearman');
fprintf(fileID, 'Pleasure vs. Dominance:     r = %.2f,   p = %.4f\n', r1, p1);
rF = r1;

% Compute and write correlations
[r1, p1] = corr(sam.Dominance(sam.Gender == 'male'), sam.Arousal(sam.Gender == 'male'), 'Type', 'Spearman');
fprintf(fileID, 'Dominance vs. Arousal:     r = %.2f,   p = %.4f\n', r1, p1);
rF = r1;


% Print header
fprintf(fileID, '\n\n--- Correlations by Valence and Gender ---\n');

% Compute and write correlations
[r1, p1] = corr(sam_pos.Pleasure(fp), sam_pos.Arousal(fp), 'Type', 'Spearman');
fprintf(fileID, '\nPOSITIVE:\n\nWomen: \nPleasure vs. Arousal:     r = %.2f,   p = %.4f\n', r1, p1);
rPF = r1;

% Compute and write correlations
[r1, p1] = corr(sam_pos.Pleasure(fp), sam_pos.Dominance(fp), 'Type', 'Spearman');
fprintf(fileID, 'Pleasure vs. Dominance:     r = %.2f,   p = %.4f\n', r1, p1);
rPF = r1;

% Compute and write correlations
[r1, p1] = corr(sam_pos.Arousal(fp), sam_pos.Dominance(fp), 'Type', 'Spearman');
fprintf(fileID, 'Arousal vs. Dominance:     r = %.2f,   p = %.4f\n', r1, p1);
rPF = r1;


% Compute and write correlations
[r1, p1] = corr(sam_pos.Pleasure(mp), sam_pos.Arousal(mp), 'Type', 'Spearman');
fprintf(fileID, '\nMen: \nPleasure vs. Arousal:     r = %.2f,   p = %.4f\n', r1, p1);
rPM = r1;

% Compute and write correlations
[r1, p1] = corr(sam_pos.Pleasure(mp), sam_pos.Dominance(mp), 'Type', 'Spearman');
fprintf(fileID, 'Pleasure vs. Dominance:     r = %.2f,   p = %.4f\n', r1, p1);
rPM = r1;

% Compute and write correlations
[r1, p1] = corr(sam_pos.Dominance(mp), sam_pos.Arousal(mp), 'Type', 'Spearman');
fprintf(fileID, 'Dominance vs. Arousal:     r = %.2f,   p = %.4f\n', r1, p1);
rPM = r1;


% Compute and write correlations
[r1, p1] = corr(sam_neg.Pleasure(fn), sam_neg.Arousal(fn), 'Type', 'Spearman');
fprintf(fileID, '\n\nNEGATIVE:\n\nWomen:\nPleasure vs. Arousal:     r = %.2f,   p = %.4f\n', r1, p1);
rNF = r1;

% Compute and write correlations
[r1, p1] = corr(sam_neg.Pleasure(fn), sam_neg.Dominance(fn), 'Type', 'Spearman');
fprintf(fileID, 'Pleasure vs. Dominance:     r = %.2f,   p = %.4f\n', r1, p1);
rNF = r1;

% Compute and write correlations
[r1, p1] = corr(sam_neg.Dominance(fn), sam_neg.Arousal(fn), 'Type', 'Spearman');
fprintf(fileID, 'Dominance vs. Arousal:     r = %.2f,   p = %.4f\n', r1, p1);
rNF = r1;


% Compute and write correlations
[r1, p1] = corr(sam_neg.Pleasure(mn), sam_neg.Arousal(mn), 'Type', 'Spearman');
fprintf(fileID, '\nMen:\nPleasure vs. Arousal:     r = %.2f,   p = %.4f\n', r1, p1);
rNM = r1;

% Compute and write correlations
[r1, p1] = corr(sam_neg.Pleasure(mn), sam_neg.Dominance(mn), 'Type', 'Spearman');
fprintf(fileID, 'Pleasure vs. Dominance:     r = %.2f,   p = %.4f\n', r1, p1);
rNM = r1;

% Compute and write correlations
[r1, p1] = corr(sam_neg.Dominance(mn), sam_neg.Arousal(mn), 'Type', 'Spearman');
fprintf(fileID, 'Dominance vs. Arousal:     r = %.2f,   p = %.4f\n', r1, p1);
rNM = r1;


% Close file and figures
fclose(fileID);
close all;